kind: pipeline
name: default

steps:
- name: setup
  image: gcr.io/kubebuilder/thirdparty-linux:1.16.4
  commands:
    - cp /kubebuilder_linux_amd64.tar.gz $DRONE_WORKSPACE

- name: test
  image: golang:latest
  environment:
    GOFLAGS: -mod=vendor
  commands:
    - tar -xf kubebuilder_linux_amd64.tar.gz -C /usr/local
    - GOFLAGS="" make controller-gen
    - make test

- name: build-container
  image: plugins/docker
  settings:
    repo: bradbeam/lightstream
    auto_tag: true
    dry_run: true

- name: push-container
  image: plugins/docker
  settings:
    username: bradbeam
    password:
      from_secret: docker_password
    repo: bradbeam/lightstream
    auto_tag: true
  when:
    event:
      exclude:
      - pull_request
