# permissions to do viewer envwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envwatcher-viewer-role
rules:
- apiGroups:
  - lightwatch.vigilant.dev
  resources:
  - envwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lightwatch.vigilant.dev
  resources:
  - envwatchers/status
  verbs:
  - get
